version: '2'

services:
  zookeeper1:
    image: athlinks/confluent-zookeeper
    hostname: zookeeper1
    mem_limit: 1024m
    memswap_limit: 0m
    environment:
      MYID: "1"
      OTHER_NODES: "3=zookeeper3,2=zookeeper2"
    ports:
      - "2181"
      - "2888"
      - "3888"

  zookeeper2:
    image: athlinks/confluent-zookeeper
    hostname: zookeeper2
    mem_limit: 1024m
    memswap_limit: 0m
    environment:
      MYID: "2"
      OTHER_NODES: "1=zookeeper1,3=zookeeper3"
    ports:
      - "2181"
      - "2888"
      - "3888"

  zookeeper3:
    image: athlinks/confluent-zookeeper
    hostname: zookeeper3
    mem_limit: 1024m
    memswap_limit: 0m
    environment:
      MYID: "3"
      OTHER_NODES: "1=zookeeper1,2=zookeeper2"
    ports:
      - "2181"
      - "2888"
      - "3888"

  hadoop-journalnode1:
    image: athlinks/hadoop
    hostname: hadoop-journalnode1
    environment:
      - "SERVICE_NAME=hadoop-journalnode"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=JOURNALNODE1"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8485"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  hadoop-journalnode2:
    image: athlinks/hadoop
    hostname: hadoop-journalnode2
    environment:
      - "SERVICE_NAME=hadoop-journalnode"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=JOURNALNODE2"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8485"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  hadoop-journalnode3:
    image: athlinks/hadoop
    hostname: hadoop-journalnode3
    environment:
      - "SERVICE_NAME=hadoop-journalnode"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=JOURNALNODE3"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8485"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  hadoop-namenode1:
    image: athlinks/hadoop
    hostname: hadoop-namenode1
    environment:
      - "SERVICE_NAME=hadoop-master"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=NAMENODE1"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8088"
      - "9000:9000"
      - "50070:50070"
      - "50090"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - hadoop-journalnode1
      - hadoop-journalnode2
      - hadoop-journalnode3

  hadoop-namenode2:
    image: athlinks/hadoop
    hostname: hadoop-namenode2
    environment:
      - "SERVICE_NAME=hadoop-master"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=NAMENODE2"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8088"
      - "9000"
      - "50071:50070"
      - "50090"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - hadoop-journalnode1
      - hadoop-journalnode2
      - hadoop-journalnode3

  hadoop-resourcemanager1:
    image: athlinks/hadoop
    hostname: hadoop-resourcemanager1
    environment:
      - "SERVICE_NAME=hadoop-resourcemanager"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=RESOURCEMANAGER"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8088:8088"
      - "9000"
      - "50070"
      - "50090"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - hadoop-namenode1
      - hadoop-namenode2

  hadoop-resourcemanager2:
    image: athlinks/hadoop
    hostname: hadoop-resourcemanager2
    environment:
      - "SERVICE_NAME=hadoop-resourcemanager"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=RESOURCEMANAGER"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8088"
      - "9000"
      - "50070"
      - "50090"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - hadoop-namenode1
      - hadoop-namenode2

  hadoop-datanode1:
    image: athlinks/hadoop
    hostname: hadoop-datanode1
    environment:
      - "SERVICE_NAME=hadoop-datanode"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=DATANODE"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8088"
      - "9000"
      - "50070"
      - "50090"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - hadoop-namenode1
      - hadoop-namenode2

  hadoop-datanode2:
    image: athlinks/hadoop
    hostname: hadoop-datanode2
    environment:
      - "SERVICE_NAME=hadoop-datanode"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=DATANODE"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8088"
      - "9000"
      - "50070"
      - "50090"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - hadoop-namenode1
      - hadoop-namenode2

  hadoop-nodemanager1:
    image: athlinks/hadoop
    hostname: hadoop-nodemanager1
    environment:
      - "SERVICE_NAME=hadoop-nodemanager"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=NODEMANAGER"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8088"
      - "9000"
      - "50070"
      - "50090"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - hadoop-namenode1
      - hadoop-namenode2
      - hadoop-resourcemanager1
      - hadoop-resourcemanager2

  hadoop-nodemanager2:
    image: athlinks/hadoop
    hostname: hadoop-nodemanager2
    environment:
      - "SERVICE_NAME=hadoop-nodemanager"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=NODEMANAGER"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8088"
      - "9000"
      - "50070"
      - "50090"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - hadoop-namenode1
      - hadoop-namenode2
      - hadoop-resourcemanager1
      - hadoop-resourcemanager2

  hadoop-httpfs:
    image: athlinks/hadoop
    hostname: hadoop-httpfs
    environment:
      - "SERVICE_NAME=hadoop-httpfs"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=HTTPFS"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "14000:14000"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - hadoop-namenode1
      - hadoop-namenode2
      - hadoop-datanode1
      - hadoop-datanode2

  hadoop-client:
    image: athlinks/hadoop
    hostname: hadoop-client
    environment:
      - "SERVICE_NAME=hadoop-client"
      - "SERVICE_TAGS=syracuse-dev"
      - "HADOOP_ROLE=CLIENT"
      - "HADOOP_JOURNALNODE1=hadoop-journalnode1"
      - "HADOOP_JOURNALNODE2=hadoop-journalnode2"
      - "HADOOP_JOURNALNODE3=hadoop-journalnode3"
      - "HADOOP_NAMENODE1=hadoop-namenode1"
      - "HADOOP_NAMENODE2=hadoop-namenode2"
      - "HADOOP_RESOURCEMANAGER1=hadoop-resourcemanager1"
      - "HADOOP_RESOURCEMANAGER2=hadoop-resourcemanager2"
      - "HADOOP_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - hadoop-namenode1
      - hadoop-namenode2
      - hadoop-datanode1
      - hadoop-datanode2
      - hadoop-resourcemanager1
      - hadoop-resourcemanager2
      - hadoop-nodemanager1
      - hadoop-nodemanager2
